### ISSUE TITLE
[查看工時頁面] 意見回饋總整理

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#294]
- [x] 工時查詢頁面搜尋欄的自動完成功能 #292 
- [x] 切換至最新工時（/#latest）時，搜尋框應該清空， radio 要回復預設值 #293 
- [x] 當切換至 search-and-group (by job title or by company) 的時候，搜尋框與 radio 要相對應改變 #293 
- [x] 加班頻率的部份，0,1,2,3 文字修正  #297 
- [x] 以公司/職稱搜尋工時的結果，當只有一個group時，就直接展開，超過一個group時，全部縮起來 #296 
- [x] 以公司/職稱蒐尋工時的結果中，每一個group裡面的排序方式，由時間排序改為由名稱(職稱/公司)排序 https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/122 
- [x] 最新工時的資料表格，上方加上「最新工時」的標題 #302 
- [x] 以公司查詢工時資料的表格，展開的狀態下，直接顯示加班費/補休欄位。資料不足五筆以 - 顯示，並提示需5筆以上才會顯示，超過五筆則顯示各個數量。 #301 
- [x] 返回搜尋欄的icon，修改為至頂端的icon，並調整顏色。 #302
- [x] 支援iOS 8 #299

**Comment by wutingy** [comment]
加班 0123 我以為是暫時放的...應顯示文字。

> 最新工時的頁面，要不要有個大大的字提醒是最新工時的頁面呢?

我覺得需要

> 同一間公司要超過五筆資訊，才會顯示加班費、補休資訊

這表格右下角原本有個圖表註解

**Comment by mark86092** [comment]
Done

**Comment by mark86092** [comment]
Oops, #292

**Comment by barry800414** [comment]
Done
