### ISSUE TITLE
前端更新總整理

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#371]
前端更新總整理
===

先把所有的任務分三大類: 
* 查詢資訊權限:
    * 進入查詢頁面時，檢查使用者是否有查詢資訊的權限，並做相對應的介面提示與反應
    * 在上傳薪時資訊時，若有使用者推薦字串，需一併上傳
* 首頁表單區新增欄位
    * 新增薪資、該職位相關工作經驗、雇用型態、性別等欄位
    * 表單前端檢查
* 查詢資訊頁面更新
    * 新增薪資、該職位相關工作經驗、雇用型態、性別、估計時薪、參考時間等欄位
    * 新增排序功能: 以估計時薪、一週工時、資料上傳時間排序
    * 以公司、職稱查詢資訊時，搜尋方式以及群組方式的更新

### 【查詢資訊權限】
- [x] 首頁表單區上傳資訊時，如果有使用者推薦字串，需將使用者字串上傳 issue: #372
- [x] 查詢頁面 - 檢查使用者是否有查詢資訊的權限。 
      一開始先限制查詢資訊功能
      若沒有權限，顯示要留一筆或邀請使用者留一筆的提示訊息。
      若有權限，則開放查詢資訊功能  issue: #373
- [x] 查詢頁面 - 限制/開放 以職稱&以公司查詢的功能 issue: #374
- [x] 查詢頁面 - 限制/開放 單筆資訊查詢 issue: #375
- [x] 如果使用者有權限，打後端API的時候，要上傳 access_token

### 【首頁表單區新增欄位】
- [x] 新增欄位 - style的部份  PR: #351
- [x] 欄位驗證  PR: #354 

### 【查詢資訊頁面更新】
- [x] 單筆薪時資訊，排序功能、欄位更新、網址設計 issue: #376
- [x] 以公司查詢，排序功能、欄位更新、網址設計 issue: #377
- [x] 以職稱查詢，排序功能、欄位更新、網址設計 issue: #378
- [x] 快速連結的按鈕 #391 

### 【其它】
- [ ] 參考時間、估計時薪的提示字 
- [ ] 網頁上的文案修正

可能還有更多，請協助補上
